### ISSUE TITLE
Feat: Extra Mr. Do screen still image

### ISSUE THREAD

**Issue by plasticbugs** [plasticbugs/mrdoarcade#3]
Full screen image displays without bugs on EXTRA. https://forums.atariage.com/topic/167208-mr-do/#findComment-2067774

And

https://forums.atariage.com/topic/376824-mr-do-arcade-version/#findComment-5577023

**Comment by artrag** [comment]
Give me this week end and I will give you can source file for the static images you need

**Comment by plasticbugs** [comment]
Thank you @artrag . This is done!
